[package]
name = "scrabber"
version = "0.1.0"
authors = ["Aslam Ahammed <aslamplr@gmail.com>"]

[dependencies]
regex = "1.0.0"
reqwest = "0.8.6"
scraper = "0.7.0"
prettytable-rs = "^0.6"
clap = "2.31.2"
chrono = "0.4"
openssl-probe = "0.1.2"

[profile.release]
lto = true
